export enum TokenType {
    String = "string",
    Number = "number",
    Comma = "comma",
    Colon = "colon",
    Dot = "dot",
    Plus = "plus",
    Minus = "minus",
    GreaterThan = "greater-than",
    LessThan = "less-than",
    ParenthesisLeft = "parenthesis-left",
    ParenthesisRight = "parenthesis-right",
    BlockOpen = "block-open",
    BlockAlternate = "block-alternate",
    BlockClose = "block-close",
    Hash = "hash",
    Slash = "slash",
    Star = "star",
    Bang = "bang",
    DelimiterLeft = "delimiter-left",
    DelimiterRight = "delimiter-right",
    Constant = "constant",
    Identifier = "identifier",
    Reserved = "reserved",
    Equal = "equal",
    NotEqual = "not-equal"
}