export enum TokenType {
    String = "string",
    Number = "number",
    Comma = "comma",
    Colon = "colon",
    Dot = "dot",
    Plus = "plus",
    GreaterThan = "greater-than",
    LessThan = "less-than",
    ParenthesisLeft = "parenthesis-left",
    ParenthesisRight = "parenthesis-right",
    BlockOpen = "block-open",
    BlockAlternate = "block-alternate",
    BlockClose = "block-close",
    Hash = "hash",
    Slash = "slash",
    DelimiterLeft = "delimiter-left",
    DelimiterRight = "delimiter-right",
    Constant = "constant",
    Identifier = "identifier",
    Reserved = "reserved"
}